// <auto-generated />
namespace ppee_dataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class table_for_min_max_values : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_for_min_max_values));
        
        string IMigrationMetadata.Id
        {
            get { return "202112261628007_table_for_min_max_values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
