// <auto-generated />
namespace ppee_dataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class forecast_values_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forecast_values_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202112271451506_forecast_values_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
